travis:
  secure:
    BINSTAR_TOKEN: vXVK+PECwNh6edYUZ3ZTOR1S59pgVYWrEm3G+G3sINu2iaUzLtBjStSCSK5y3Nao4EdojPg6C2POoWmBU7TWBpnt3fMLLZlIZsC2l7zTKvUmq0u3YDfXeP2DGgAbJ9Ed5vDm1au3v3fISu74+OeQJntLZzB6UWD/qd/ZDvcO1TTp0jw1bo2JgKESfUpH4iRbzXqGYkpSrwxS52mLZzPgTE7LoDznaD43qDq140//nnbov4CjmCUqdVaEWnziRKe7w+2/SAF7aSQfR11JFPCZsI03qJEEtsZ3HsxGcKT771ntHNgDCAyL75rR3+TjXBrEToivW0orpAQoWhjYywipNWj8x9q1SGtLEpI1goKL4pl8Uc+6pZo0oWg3UlA7sIEKp+EpOllQ6XxHrC4jZ5YUZDTI5UGKw+DlWsx/BQKT4QgWmDILM665nrXGUnrbOmMTtR3BwNJ0WvU/6Kd4f04DZftdAOZnn6hVSlT55NWzYlTinS8G4oSZ1TDmdXGQl/dhHrn4bmDTW7ltIQxyUO7t/fZto0NrnJGSOm4Ge3oiPKnIidhfb8PlfY86L/VZPuXKJ3EWiB8RvTywPPGhSuhuKXPlTnrsPgFP3Ue6wNeXhBXgCVtWPMETCWn2Labz+THMkik3LdLinFTCiw7Cl0lSN47dFVWWfL9JeLsjebKJbEM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
