travis:
  secure:
    BINSTAR_TOKEN: PAtPRwY3p9Vt7/Ep0+ZM41u7wO/SK+3hJhFdyfJN7R6WNi/kUm/z3l/5oPN5u+QOD3L1afkdMCSHpywnI6XkxhS8ZMpBT+IzrGq94gOrW/E8nqEmt6k1BkK1sFEL/Bm4ckhqJxawewf1r32MMmlCzVMXWV4PJ9l3dgOGxdC355163L3xGmBK33bpDcv5ywsIzt7x7Y3qLeAsaUjoJt3NSow2m2wc4ij5nDsvDib2Po3kJKOIYAdGJVai8BGiBVechljKGDConj/v29F00U7kdUIlytCkjWHoYmI6jMAe1/NYutvJJE+8BBDbZjFDKR7axRFkbJmEPn+bBt4tTlMyKVsjGCXBSBRYgoSzpu517yeovBvF/d2z/eyBUzlmeHjas1Zh2xi1iTgZDlktWS5MtpStgz2ELX/EMY7coKq9Wh4UkwN6PSyx7Xhgs2eTe0zzC+fCeZgDs2vxWFJNvMwLdRwdnoKXL0CDmjT7CV7+7yiU/6TEI0nZDulL1xtdwpT2irxX0k1gW3QjfuehtsuKaMMDsHvap4+jel2pTzpXA/wlBAZ55F3/WvINHil3cYq2phZORh5/EVHa95mcjAUoMKLzyu7xR7pvsZ3LhCmbOXM/76ISngFcFtpF2eu0Rizvv6DKkO2humAyBtZvdpyDsNbcaPLvty07j2Levpf4FCY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
